// React components built on top of the availability engine helpers

function TranscriptAvailabilities({ transcriptKey, transcript }) {
  const perParticipant = buildParticipantAvailabilities(transcript);

  return (
    <article className="transcript-card">
      <div className="transcript-header">
        <div className="transcript-title">{transcript.call_info || transcriptKey}</div>
        <div className="transcript-meta">
          Transcript {transcript.id != null ? transcript.id : transcriptKey}
        </div>
      </div>

      <div className="participants">
        {(transcript.participants || []).map((p) => (
          <span key={p.name} className="participant-pill">
            <strong>{p.name}</strong> · {p.role}
          </span>
        ))}
      </div>

      <ul className="availability-list">
        {perParticipant.size === 0 ? (
          <li>No explicit availability constraints detected in this transcript.</li>
        ) : (
          Array.from(perParticipant.entries()).map(([speaker, intervals]) => (
            <li key={speaker}>
              <span className="label">{speaker}: </span>
              {intervals.length === 0 ? (
                "no clear availabilities extracted."
              ) : (
                <ul style={{ margin: "3px 0 0 14px", paddingLeft: 0, listStyle: "disc" }}>
                  {intervals.map((iv, idx) => (
                    <li key={idx}>{formatDateTimeRange(iv.start, iv.end)}</li>
                  ))}
                </ul>
              )}
            </li>
          ))
        )}
      </ul>
    </article>
  );
}

function TranscriptSlots({ transcriptKey, transcript }) {
  const perParticipant = buildParticipantAvailabilities(transcript);
  const baseSlots = computeCommonSlots(perParticipant);
  const [copyStatus, setCopyStatus] = React.useState("");

  let commonSlots = baseSlots;
  if (baseSlots.length > 0) {
    const refined = refineFirstSlotWithTranscript(
      transcript,
      baseSlots[0],
      DEFAULT_MEETING_DURATION_MIN,
    );
    if (refined) {
      commonSlots = [refined].concat(baseSlots.slice(1));
    }
  }

  const bestSlot = commonSlots[0];
  const summary =
    "Viewing – " + (transcript.call_info || "Apartment viewing appointment");
  const description =
    "Generated by MOVA – simple heuristic assistant based on transcript availabilities.";
  const icsContent = bestSlot ? generateIcsForSlot(bestSlot, summary, description) : "";

  const handleCopy = async () => {
    if (!icsContent) return;
    try {
      await navigator.clipboard.writeText(icsContent);
      setCopyStatus("Copied to clipboard");
      setTimeout(() => setCopyStatus(""), 1800);
    } catch (err) {
      setCopyStatus("Copy failed – select text manually.");
    }
  };

  return (
    <article className="transcript-card">
      <div className="transcript-header">
        <div className="transcript-title">{transcript.call_info || transcriptKey}</div>
        <span className="badge">Computed slots</span>
      </div>

      <ul className="slot-list">
        {commonSlots.length === 0 ? (
          <li>
            No common slot satisfying the default duration was found based on the extracted
            windows.
          </li>
        ) : (
          commonSlots.map((slot, idx) => (
            <li key={idx}>
              <span className="label">{idx === 0 ? "Suggested:" : "Alternative:"}</span>{" "}
              <span className={idx === 0 ? "badge good" : "badge low-priority"}>
                {idx === 0 ? "Earliest feasible" : "Also feasible"}
              </span>{" "}
              {formatDateTimeRange(slot.start, slot.end)}
            </li>
          ))
        )}
      </ul>

      {bestSlot && (
        <div className="ics-block">
          <div className="ics-header">
            <div className="ics-header-title">
              Meeting invite (.ics content, copy into a file to import):
            </div>
            <button type="button" onClick={handleCopy}>
              Copy .ics
            </button>
            <div className="copy-status">{copyStatus}</div>
          </div>
          <textarea
            className="ics-textarea"
            readOnly
            value={icsContent}
            spellCheck="false"
          />
        </div>
      )}
    </article>
  );
}

function AssumptionsPanel() {
  return (
    <section className="panel">
      <h2>4. Technical choices & assumptions</h2>
      <div className="assumptions">
        <section>
          <h3>Time & language assumptions</h3>
          <ul>
            <li>
              All participants are assumed to be in the same timezone (your browser's local
              timezone is used when rendering dates).
            </li>
            <li>
              "Next week" is interpreted as the calendar week starting on the Monday after
              the call date.
            </li>
            <li>
              Generic periods are mapped to fixed windows: "morning" ≈ 09:00–12:00,
              "afternoon" ≈ 13:00–17:00, "late afternoon" ≈ 16:00–18:00, "evening" ≈
              18:00–21:00.
            </li>
            <li>
              The default meeting duration is {DEFAULT_MEETING_DURATION_MIN} minutes;
              overlaps shorter than this are discarded.
            </li>
          </ul>
        </section>
        <section>
          <h3>Extraction heuristics & limitations</h3>
          <ul>
            <li>
              The current version uses simple pattern matching (no external LLM at runtime)
              to detect days of week, relative expressions ("next week") and coarse
              periods ("morning").
            </li>
            <li>
              Negative statements such as "doesn't work" are treated as exclusions and are
              not added as availability.
            </li>
            <li>
              Ambiguous or very vague phrases may be ignored rather than misinterpreted;
              the UI surfaces only windows it can parse confidently.
            </li>
            <li>
              For brevity, the implementation focuses on typical scheduling phrases;
              extending the grammar to more edge cases is possible but not yet implemented.
            </li>
          </ul>
        </section>
        <section>
          <h3>Evolution ideas</h3>
          <ul>
            <li>
              Introduce an LLM-backed extraction layer with explicit, auditable prompts to
              handle more varied natural language while keeping this heuristic layer as a
              safety net.
            </li>
            <li>
              Add a notion of preference/priority (e.g. "last resort") and scoring, not
              just binary feasibility.
            </li>
            <li>
              Support multi-party scheduling across multiple transcripts and direct export
              to providers (Google Calendar links, email templates).
            </li>
          </ul>
        </section>
      </div>
    </section>
  );
}

